### ISSUE TITLE
Implement Content Vanity API

### ISSUE THREAD

**Issue by tdstein** [posit-dev/posit-sdk-py#175]
# Content Vanity API

## v0.6.0 Proposal

```python
from posit import connect

client = connect.Client()
content = client.content.get(...)

vanity = content.vanity = ...
del content.vanity

vanity.destroy()
```

**Comment by nealrichardson** [comment]
Following https://github.com/rstudio/connect/pull/27252, we should add `vanity_url` to the default `include` specification (and also add `include` to the content item GET request). Then for the `vanity_url` `@property`, if the field is not set, do `GET /__api__/v1/content/{guid}/vanity` to resolve it (that API was added in 2020: https://github.com/rstudio/connect/pull/18448). 

Ideally we should be able to distinguish between "There is no vanity URL for this content" and "I haven't asked for the vanity URL yet" so we don't make extra requests, but that's probably not a huge concern (until we learn otherwise).
