### ISSUE TITLE
Consider behavior of `find_one()` functions in the case of multiple matches

### ISSUE THREAD

**Issue by tnederlof** [posit-dev/posit-sdk-py#193]
The `find_one()` function returns the first if multiple are found. It is documented in the README here: https://github.com/posit-dev/posit-sdk-py/blob/62ff3596c56217d3f5fb2d57d95bde53f5655b4f/src/posit/connect/README.md?plain=1#L33

IMO it would be safer to error out on these functions, especially with endpoints that accept a `prefix` parameter since users may be searching with `prefix`, which can easily match multiple users inadvertently (`Users` `find_one()` searches username, first name, and last name for example).

**Comment by tdstein** [comment]
This behavior matches the `get` method signature better than the `find_one` method. 

Currently, the existing `get` methods accept a unique identifier and then raise an exception if the resource isn't found. However, this is a good reason to expand the method signature for different query patterns.

If we implement this, we should consider raising a different exception for zero results and more than one result.

**Comment by tdstein** [comment]
Relates to #294

**Comment by tdstein** [comment]
We are migrating to use `find` for retrieving a single item instead of `get` and removing `find_one` in favor of `find_by`. An additional method named `fetch` is being added which accepts query parameters to retrieve all records using conditionals supported by the server (e.g., `client.users.fetch(prefix="t")`).
