### ISSUE TITLE
Publish docs to docs.posit.co

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/posit-sdk-py#209]
Presumably we will want the docs site as a part of that and not hosted separately, as rsconnect-python does.

**Comment by tdstein** [comment]
The documentation for the latest minor release, v0.2.1, is available on Netlify. A support request has been made to route https://sdk.posit.co/python to https://posit-sdk-py.netlify.app. This subdomain pattern follows other Posit OSS sites more closely than reconnect-python.

**Comment by nealrichardson** [comment]
Is https://sdk.posit.co/python right? I would have expected it under docs.posit.co, this doesn't seem like something that should get its own subdomain, does it?

**Comment by tdstein** [comment]
I'm honestly not sure, so currently, open-source projects are listed here on docs.posit.co: https://docs.posit.co/resources/open-source.html

Technically, this project is OSS. But, it is different because it is specifically built for commercial projects.

Do you know who owns docs.posit.co? Sounds like we should discuss with the larger group.

**Comment by annikakrilov** [comment]
If this is not immediately pressing, I'd like to wait until next week to make a decision so I can discuss this with Amanda (who's OOO this week). Amanda/Ashley/I have been having conversations recently about what lives under docs and working on getting info up on the Product Docs Confluence to help clarify the decision process for other teams. That work is mostly done, but missing some decision making info - and I agree with Taylor that these docs are kind of a grey area. Open Source has historically _not_ been under docs, but those products have not been as commercially geared or as distinctly associated with the Posit Brand as the SDK content is. 

I am leaning towards thinking that these should go under docs.posit.co, but don't want to make that decision without discussing it with anyone else on the docs team since that breaks precedence with the other OSS content (and Ashley has just gone out on leave). 

If we do go with adding it under docs.posit.co, process info is here:
https://positpbc.atlassian.net/wiki/spaces/ENG/pages/825983279/Adding+a+documentation+site+under+docs.posit.co

**Comment by tdstein** [comment]
Thanks! It is not pressing, but I'm ready to make the site live. I'll follow up next week once everyone returns from OOO.

**Comment by annikakrilov** [comment]
Spoke to Taylor in the SDK meeting today, but adding here for tracking - spoke with Amanda, and we're both on board with having these docs under docs.posit.co given the digression from other open source docs
